apiVersion: v1
kind: Service
metadata:
  name: exec-intel
  namespace: exec-intel
spec:
  type: NodePort
  selector:
    app: exec-intel
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
